apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: frontend
spec:
  initcontainer:
    - name: config-loader
      image: busybox
      command: ['sh', '-c', 'cp /config//app.conf /etc/app']
      volumeMounts:
      - name: config-volume
        mountPath: /config
      - name: app-config
        mountPath: /etc/app
  container:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: app-config
        mountPath: /etc/nginx/conf.d
    livenessProbe: 
      httpGet:
        path: /health
        port: 80
  volumes:
    - name: config-volume
      configMap:
        name: app-configmap
    - name: app-config
      emptyDir: {}
